services:
  postgres:
    restart: "unless-stopped"
    image: postgres:15-alpine
    stop_grace_period: 1m
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432/tcp
    healthcheck:
      test: [ "CMD", "nc", "-z", "-v", "localhost", "5432" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      default:
        aliases:
          - cosmos-indexer
volumes:
  postgres: